# -*- coding: utf-8 -*-
"""NLP_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oDNULwgQRilMSEQVGD6-OP8cK8ulN44
"""

from google.colab import files
uploaded = files.upload()

import zipfile
import os

zip_file = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall('/content/data')

print("Files extracted to /content/data")

import os

for root, dirs, files in os.walk('/content/data'):
    for file in files:
        print(os.path.join(root, file))

import pandas as pd

df = pd.read_csv('/content/data/Amazon-Product-Reviews - Amazon Product Review (1).csv')
df.head()

df = df[['review_body', 'star_rating']]  # adjust if column names differ
df.dropna(inplace=True)

# Convert ratings to sentiment
def get_sentiment(score):
    if score <= 2:
        return 'negative'
    elif score == 3:
        return 'neutral'
    else:
        return 'positive'

df['Sentiment'] = df['star_rating'].apply(get_sentiment)
df = df.rename(columns={'review_body': 'Text', 'star_rating': 'Score'})
df.head()

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    tokens = nltk.word_tokenize(text)

    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    return " ".join(tokens)

df['Clean_Text'] = df['Text'].apply(preprocess)

df.head()

from sklearn.model_selection import train_test_split

X = df['Clean_Text']
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    stop_words='english'
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
lr_model.fit(X_train_tfidf, y_train)

lr_pred = lr_model.predict(X_test_tfidf)

from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

nb_pred = nb_model.predict(X_test_tfidf)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=300, class_weight='balanced')
model.fit(X_train_tfidf, y_train)

import pickle

pickle.dump(model, open("sentiment_model.pkl", "wb"))

from sklearn.metrics import classification_report, accuracy_score

print("Logistic Regression:\n", classification_report(y_test, lr_pred))
print("Accuracy:", accuracy_score(y_test, lr_pred))

print("\nNaive Bayes:\n", classification_report(y_test, nb_pred))
print("Accuracy:", accuracy_score(y_test, nb_pred))

# Generate predictions for the main Logistic Regression model (named 'model')
model_pred = model.predict(X_test_tfidf)
print("\nMain Logistic Regression Model:\n", classification_report(y_test, model_pred))
print("Accuracy:", accuracy_score(y_test, model_pred))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

# Use 'model_pred' which contains predictions from the main Logistic Regression model
ConfusionMatrixDisplay.from_predictions(y_test, model_pred)
plt.title('Confusion Matrix for Main Logistic Regression Model')
plt.show()

!pip install transformers

from transformers import pipeline
import numpy as np

# Balanced sampling
df = df.groupby('Sentiment').apply(lambda x: x.sample(1000)).reset_index(drop=True)

# Lightweight model
emotion_model = pipeline(
    "text-classification",
    model="bhadresh-savani/distilbert-base-uncased-emotion",
    device=-1
)

def detect_emotions_batch(texts, batch_size=64):
    texts = texts.fillna("").str[:256]

    emotions = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size].tolist()
        results = emotion_model(batch)
        emotions.extend([res['label'] for res in results])

    return emotions

df['Emotion'] = detect_emotions_batch(df['Clean_Text'])

import seaborn as sns

sns.countplot(x='Sentiment', data=df)
plt.title("Sentiment Distribution")
plt.show()

sns.countplot(x='Emotion', data=df)
plt.title("Emotion Distribution")
plt.xticks(rotation=45)
plt.show()

def refine_emotion(emotions, sentiment):
    top_emotion = emotions[0]['label']
    if sentiment == "negative" and top_emotion == "joy":
        for emo in emotions:
            if emo['label'] in ["anger", "sadness", "fear"]:
                return emo['label']
    return top_emotion

def fix_negation(text, sentiment):
    neg_words = ["not", "no", "never", "n't"]
    for word in neg_words:
        if word in text:
            if sentiment == "positive":
                return "negative"
    return sentiment

def predict_review(text):
    cleaned = preprocess(text)
    vector = tfidf.transform([cleaned])

    # Sentiment prediction
    sentiment = model.predict(vector)[0]
    sentiment = fix_negation(cleaned, sentiment)

    # Emotion prediction
    emotion_results = emotion_model(cleaned[:256], top_k=3)
    emotion = refine_emotion(emotion_results, sentiment)

    print("Review:", text)
    print("Sentiment:", sentiment)
    print("Emotion:", emotion)

predict_review("This product is amazing and I love it!")

!pip install gensim

import gensim
from gensim.models import Word2Vec
import numpy as np

tokenized_text = df['Clean_Text'].apply(lambda x: x.split())

w2v_model = Word2Vec(
    sentences=tokenized_text,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

def get_avg_word2vec(tokens, model, vector_size):
    vectors = []

    for word in tokens:
        if word in model.wv:
            vectors.append(model.wv[word])

    if len(vectors) == 0:
        return np.zeros(vector_size)

    return np.mean(vectors, axis=0)

X_w2v = np.array([
    get_avg_word2vec(tokens, w2v_model, 100)
    for tokens in tokenized_text
])

from sklearn.model_selection import train_test_split

X_train_w2v, X_test_w2v, y_train_w2v, y_test_w2v = train_test_split(
    X_w2v, df['Sentiment'], test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=300, class_weight='balanced')
model.fit(X_train_tfidf, y_train)
w2v_model_lr = LogisticRegression(max_iter=200)
w2v_model_lr.fit(X_train_w2v, y_train_w2v)

import pickle

pickle.dump(model, open("sentiment_model.pkl", "wb"))

print(X_test_w2v.shape)
print(y_test_w2v.shape)
# Generate predictions first
w2v_pred = w2v_model_lr.predict(X_test_w2v)

# Then print results
from sklearn.metrics import classification_report, accuracy_score

print("Word2Vec Model:\n")
print(classification_report(y_test_w2v, w2v_pred))
print("Accuracy:", accuracy_score(y_test_w2v, w2v_pred))

from sklearn.model_selection import train_test_split

# Re-create the original y_test for TF-IDF models as it was overwritten.
# X and y still hold the full dataset's clean text and sentiment before sampling.
_, _, _, y_test_tfidf_original = train_test_split(X, y, test_size=0.2, random_state=42)

print("TF-IDF Accuracy:", accuracy_score(y_test_tfidf_original, model_pred))
print("Word2Vec Accuracy:", accuracy_score(y_test_w2v, w2v_pred))

import matplotlib.pyplot as plt

# Re-create the original y_test for TF-IDF models as it was overwritten.
# X and y still hold the full dataset's clean text and sentiment before sampling.
_, _, _, y_test_tfidf_original = train_test_split(X, y, test_size=0.2, random_state=42)

models = ['TF-IDF (LR)', 'Word2Vec (LR)']
accuracies = [
    accuracy_score(y_test_tfidf_original, model_pred),
    accuracy_score(y_test_w2v, w2v_pred)
]

plt.bar(models, accuracies)
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.show()

!pip install streamlit pyngrok

import pickle

# Save TF-IDF
pickle.dump(tfidf, open("tfidf.pkl", "wb"))

# Save main Logistic Regression model (formerly SVM in older versions of the notebook)
pickle.dump(model, open("sentiment_model.pkl", "wb"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import re
# import nltk
# import matplotlib.pyplot as plt
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# from transformers import pipeline
# 
# # Download NLTK
# nltk.download('stopwords')
# nltk.download('punkt')
# nltk.download('wordnet')
# 
# # Load models
# tfidf = pickle.load(open("tfidf.pkl", "rb"))
# model = pickle.load(open("sentiment_model.pkl", "rb"))
# 
# # ✅ Improved Emotion Model
# emotion_model = pipeline(
#     "text-classification",
#     model="j-hartmann/emotion-english-distilroberta-base",
#     device=-1
# 
# )
# 
# # Preprocessing
# stop_words = set(stopwords.words('english'))
# lemmatizer = WordNetLemmatizer()
# 
# def preprocess(text):
#     text = text.lower()
#     text = re.sub(r'[^a-zA-Z]', ' ', text)
#     tokens = nltk.word_tokenize(text)
#     tokens = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words]
#     return " ".join(tokens)
# 
# # ✅ Emotion refinement logic
# def refine_emotion(emotions, sentiment):
#     top_emotion = emotions[0]['label']
# 
#     # Fix incorrect "joy" for negative sentiment
#     if sentiment == "negative" and top_emotion == "joy":
#         for emo in emotions:
#             if emo['label'] in ["anger", "sadness", "fear"]:
#                 return emo['label']
# 
#     return top_emotion
# 
# def fix_negation(text, sentiment):
#     neg_words = ["not", "no", "never", "n't"]
# 
#     for word in neg_words:
#         if word in text:
#             if sentiment == "positive":
#                 return "negative"
# 
#     return sentiment
# # Page config
# st.set_page_config(page_title="Sentiment Analyzer", layout="wide")
# 
# # Title
# st.markdown("<h1 style='text-align: center; color: #4CAF50;'>🛍️ Product Review Sentiment & Emotion Analyzer</h1>", unsafe_allow_html=True)
# st.markdown("### Analyze customer reviews with AI")
# 
# # Input
# user_input = st.text_area("✍️ Enter your review:", height=150)
# 
# if st.button("🔍 Analyze Review"):
# 
#     if user_input.strip() == "":
#         st.warning("Please enter a review.")
#     else:
#         cleaned = preprocess(user_input)
#         vector = tfidf.transform([cleaned])
# 
#         # Sentiment prediction
#         sentiment = model.predict(vector)[0]
#         sentiment = fix_negation(cleaned, sentiment)
# 
#         probs = model.predict_proba(vector)
#         confidence = round(max(probs[0]), 2)
# 
#         # Emotion prediction (top 3)
#         emotion_results = emotion_model(cleaned[:256], top_k=3)
#         emotion = refine_emotion(emotion_results, sentiment)
#         emotion_score = round(emotion_results[0]['score'], 2)
# 
#         # Layout
#         col1, col2 = st.columns(2)
# 
#         # Sentiment display
#         with col1:
#             st.markdown("### 📊 Sentiment")
#             if sentiment == "positive":
#                 st.success(f"😊 {sentiment.upper()}")
#             elif sentiment == "negative":
#                 st.error(f"😡 {sentiment.upper()}")
#             else:
#                 st.warning(f"😐 {sentiment.upper()}")
# 
#         # Emotion display
#         with col2:
#             st.markdown("### 🎭 Emotion")
#             st.info(f"{emotion} (Confidence: {emotion_score})")
# 
#         # Divider
#         st.markdown("---")
# 
#         # Emotion confidence chart
#         st.markdown("### 📈 Top Emotion Scores")
#         st.write(f"Confidence: {confidence}")
#         labels = [e['label'] for e in emotion_results]
#         scores = [e['score'] for e in emotion_results]
# 
#         fig, ax = plt.subplots()
#         ax.bar(labels, scores)
#         ax.set_ylim(0, 1)
#         st.pyplot(fig)
# 
# # Sidebar
# st.sidebar.title("📌 About")
# st.sidebar.info("""
# This project uses:
# - TF-IDF + SVM for Sentiment Analysis
# - Transformer model for Emotion Detection
# - NLP preprocessing pipeline
# 
# Built for NLP Mini Project 🚀
# """)

from pyngrok import ngrok

ngrok.set_auth_token("3BKy33UFJKIAQ66HzvIVmHQGizc_2XLcoTB59e11guKqvJm1T")  # ✅ ONLY TOKEN

!streamlit run app.py &>/dev/null &

public_url = ngrok.connect(8501)
print(public_url)

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Sentiment', data=df)
plt.title("Sentiment Distribution")
plt.show()

sns.countplot(x='Emotion', data=df)
plt.title("Emotion Distribution")
plt.xticks(rotation=45)
plt.show()

cross_tab = pd.crosstab(df['Sentiment'], df['Emotion'])

cross_tab.plot(kind='bar', stacked=True)
plt.title("Sentiment vs Emotion")
plt.show()

df['Length'] = df['Clean_Text'].apply(len)

sns.boxplot(x='Sentiment', y='Length', data=df)
plt.title("Review Length vs Sentiment")
plt.show()

!pip install wordcloud

from wordcloud import WordCloud

text = " ".join(df['Clean_Text'])

wordcloud = WordCloud(width=800, height=400).generate(text)

plt.imshow(wordcloud)
plt.axis('off')
plt.show()